# Generated by Django 3.2.5 on 2021-08-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210827_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
    ]
