# Generated by Django 3.2.5 on 2021-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
