# Generated by Django 3.2.5 on 2021-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
