# Generated by Django 3.2.5 on 2021-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20210828_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
