# Generated by Django 3.2.6 on 2021-09-17 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20210828_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 11, 34, 53, 271048)),
        ),
        migrations.AddField(
            model_name='story',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 17, 11, 34, 53, 270284)),
        ),
    ]
