# Generated by Django 3.2.5 on 2021-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_story_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
