# Generated by Django 3.2.5 on 2021-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='story_count',
            field=models.IntegerField(default=0),
        ),
    ]
