# Generated by Django 3.2.5 on 2021-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_story_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='story_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
